<?php

namespace Kita\Bundle\BushimeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RapportSportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportSportRepository extends EntityRepository
{
}
