kitabushime_accueil:
  path: /
  defaults: { _controller: KitaBushimeBundle:Tracker:index }
  
kitabushime_aliments:
  path: /aliments
  defaults: { _controller: KitaBushimeBundle:Tracker:aliments }
  
kitabushime_ajouteraliments:
  path: /aliments/ajouter
  defaults: { _controller: KitaBushimeBundle:Tracker:ajouterAliment }

kitabushime_modifieraliments:
  path: /aliments/modifier/{id}
  defaults: { _controller: KitaBushimeBundle:Tracker:modifierAliment }
  
kitabushime_supprimeraliments:
  path: /aliments/supprimer/{id}
  defaults: { _controller: KitaBushimeBundle:Tracker:supprimerAliment }