parameters:
#    kita_bushime.example.class: Kita\Bundle\BushimeBundle\Example

services:
#    kita_bushime.example:
#        class: %kita_bushime.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
